# Generated by Django 5.1.5 on 2025-01-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_mailshot",
                    models.DateTimeField(verbose_name="Первая отправка"),
                ),
                (
                    "last_mailshot",
                    models.DateTimeField(verbose_name="Окончание отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Завершена"),
                            ("2", "Создана"),
                            ("3", "Запущена"),
                        ],
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=50, verbose_name="Тема письма")),
                ("content", models.TextField(verbose_name="Тело письма")),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="ФИО получателя"),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="MailshotTry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("try_time", models.DateTimeField(verbose_name="Время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Успешно"), ("2", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("response", models.TextField(verbose_name="Ответ сервера")),
                (
                    "mailshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailshot.mailshot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mailshot",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailshot.message"
            ),
        ),
        migrations.AddField(
            model_name="mailshot",
            name="receivers",
            field=models.ManyToManyField(to="mailshot.recipient"),
        ),
    ]
