# Generated by Django 5.1.5 on 2025-01-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailshot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "сообщение", "verbose_name_plural": "сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "получатель", "verbose_name_plural": "получатели"},
        ),
    ]
