# Generated by Django 5.1.5 on 2025-01-22 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailshot", "0002_alter_message_options_alter_recipient_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("try_time", models.DateTimeField(verbose_name="Время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Успешно"), ("2", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("response", models.TextField(verbose_name="Ответ сервера")),
                (
                    "mailshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailshot.mailshot",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MailshotTry",
        ),
    ]
