# Generated by Django 5.1.5 on 2025-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailshot", "0003_attempt_delete_mailshottry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailshot",
            options={"verbose_name": "рассылка", "verbose_name_plural": "рассылки"},
        ),
        migrations.RenameField(
            model_name="mailshot",
            old_name="receivers",
            new_name="recipient",
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failure", "Не успешно")],
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("completed", "Завершена"),
                    ("started", "Запущена"),
                ],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
