# Generated by Django 5.1.5 on 2025-03-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailshot",
            "0005_alter_attempt_options_mailshot_owner_message_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailshot",
            options={
                "permissions": [("can_view_mailshot", "Can view mailshot")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_message", "Can view message")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_view_recipient", "Can view recipient")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
