# Generated by Django 5.1.5 on 2025-03-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailshot", "0006_alter_mailshot_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailshot",
            options={
                "permissions": [("can_stop_mailshot", "Can stop mailshot")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_message_list", "Can view message list")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_view_recipient_list", "Can view recipient list")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
