# Generated by Django 5.1.5 on 2025-03-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailshot", "0007_alter_mailshot_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="try_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="mailshot",
            old_name="last_mailshot",
            new_name="end_mailshot",
        ),
        migrations.RenameField(
            model_name="mailshot",
            old_name="first_mailshot",
            new_name="start_mailshot",
        ),
    ]
