# Generated by Django 5.1.5 on 2025-03-02 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailshot", "0008_rename_try_time_attempt_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailshot",
            options={
                "ordering": ["message", "owner"],
                "permissions": [("can_stop_mailshot", "Can stop mailshot")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="mailshot",
            name="recipient",
        ),
        migrations.AddField(
            model_name="mailshot",
            name="recipients",
            field=models.ManyToManyField(
                to="mailshot.recipient", verbose_name="Получатели рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="mailshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt",
                to="mailshot.mailshot",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailshot",
            name="end_mailshot",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Окончание отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailshot",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mailshot.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailshot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailshot",
            name="start_mailshot",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Первая отправка"
            ),
        ),
    ]
