# Generated by Django 5.1.5 on 2025-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(
                default=False, verbose_name="Пользователь заблокирован"
            ),
        ),
    ]
